language: node_js
node_js:
  - "6"
  - "node"
services:
  - docker
before_install:
  - echo "'@progress:registry'=https://registry.npm.telerik.com/" echo "//registry.npmjs.org/:_authToken=\$NPM_TOKEN" > .npmrc
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  # Updating NPM to relevant version >= 3 on Node.JS LTS
  - npm i -g npm@^3
script:
  - npm run test
sudo: required
